### ISSUE TITLE
Error is step List all team Shifts

### ISSUE THREAD

**Issue by Ruftie** [codycodes/microsoft_power_automate#2]
i am very happy, with your Flow.

But i keep running in the same error and cant seem to find the  solution.
Could you please be kind enough to take a look?

![error](https://user-images.githubusercontent.com/60474547/73457591-2ab51800-4374-11ea-8050-4e0d2632c735.jpg)

**Comment by codycodes** [comment]
Hi Ruftie!

I don't think I can reproduce your issue exactly on my end, but there might be some things I can help with. For the _List teams_ action do you get any output? For me one of the entries looks like the following:
![image](https://user-images.githubusercontent.com/8005593/73469122-b3af5d80-433a-11ea-82f0-d4d13bae187b.png)
 
If you get this output then I think you'll be able to proceed to the next steps; otherwise you can post in the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) for help as the Teams connector is still in preview.

I'm going to assume this is the issue as the `Path` field above doesn't appear to have a Team ID in the request. This flow attempts to make it easy for you to get the Team ID via the name of your team. If you supply a Team Name that doesn't match the actual name of your team, it will not match to a Team ID and it's possible the following error would occur. If you go to the screenshot I posted of the action above from the failed flow run, you can use the `displayName` field as the value which goes into the `USER INPUT:  Microsoft Teams Name (must already be created in Teams!)` variable. There might be something prepended to it depending on your organization, so if your Team's name is `crw` it may actually be `og_crw`. It will show the same name in Teams as it does in the `displayName` field.

Just so you can see, this is what mine evaluates to and is the actual name of my Team:

![image](https://user-images.githubusercontent.com/8005593/73470270-751aa280-433c-11ea-9ea0-710b3a9435ae.png)

**Comment by Ruftie** [comment]
Hi Cody,

Thank you for your reply, yes i am getting output for _List teams_  see below.
![error2](https://user-images.githubusercontent.com/60474547/73519313-02272f80-4401-11ea-9e6e-2fabb47d69c7.jpg)
As you can see my job is finished within a second and yours in two so i think that should be the case.

**Comment by Ruftie** [comment]
Fix it, made a mistake in the name field.... Got it to work for one user how do I do it for the complete organization? Do I need to run it with admin privileges on the calendars or the complete flow as admin?

**Comment by codycodes** [comment]
I'm not sure what you mean; using the variable `USER INPUT: Get everyone's shifts (true) or just my shifts (false)` I'm able to see my teammates shifts on the calendar I specify. When you say 'one user' do you mean yourself or another member of your organization? I'm not sure if you want to attempt to deploy this flow for other users in your org or if you want to see all the shifts of members for your entire organization on one calendar. Please give more specifics in a new issue and I'll do my best to help you out.

Probably whatever can be viewed in shifts is the same data the API will retrieve. If there are more people on your Team and their shifts aren't showing up with this flow, but they are showing up in Shifts, there could be a permissions issue or a bug in the API.

**Comment by Ruftie** [comment]
HI Cody,

I would like to put every users own shifts in there own O365 calendar
(Agenda in Dutch) so that the can see there shifts on there own mobile
device.

Gr Rufite

Op vr 31 jan. 2020 om 17:01 schreef Cody Gagnon <notifications@github.com>:

**Comment by codycodes** [comment]
Currently the flow doesn't support that behavior; only everyone's shifts or my shifts. I'm don't plan on implementing this feature but it is possible to change the flow to suit your needs.

First you can change the `Create events for everyone's shifts` action and add a `switch` action that can change based on the user's name in O365. An issue that may arise with this approach is if the user's name changes then this code will break; but it may be easier to input and compare their names than to use the user's actual identifier (though this would be a better solution):
![image](https://user-images.githubusercontent.com/8005593/73594610-b047dd80-44c4-11ea-9290-fab40b55966c.png)

You'll also need to delete the events off of each of these calendars; you need to change the `User Input: Calendar Name` variable from a String type to an array, and then you can iterate through each with the `Apply to each` action to map each of the calendar ID Strings and delete all the events from each of these calendars using this calendar ID. Good luck!
